### ISSUE TITLE
training and testing frames in ORR dataset

### ISSUE THREAD

**Issue by Afreshbird** [JessieW0806/Bi-LRFusion#2]
First of all, thank you for your contributions. I have a question about the ORR dataset.
In your paper, ORR is split  into 7,064 frames for training and 1,760 frames for validation. But MVDet split into 7,071 for training and 1,791 for testing. Why not be consistent?

**Comment by JessieW0806** [comment]
Thank you for your attention. Sorry for the late response. In fact, we use the train.txt as our training split. The reference is at https://github.com/qiank10/MVDNet/blob/main/data/RobotCar/ImageSets/train.txt#L7064.

**Comment by Afreshbird** [comment]
Ok, Thank you for you reply.
